"""Automorphism group computation for combinatorial dart maps.

The automorphism group ``Aut(dm)`` consists of all bijections on dart indices
that commute with both ``sigma`` (vertex rotation) and ``alpha`` (edge
involution) — or commute with ``alpha`` while reversing ``sigma`` to
``sigma⁻¹`` for orientation-reversing symmetries.

Generators are computed via pynauty (which calls nauty in C).  The group
order is read directly from nauty's output.  ``automorphism_group_order`` is
a pure-Python BFS utility useful for validation in tests.
"""

from __future__ import annotations

from polygraph.interop.pynauty_adapter import (
    dartmap_automorphisms as _dartmap_automorphisms,
)
from polygraph.structures.dart_map import DartMap
from polygraph.structures.permutation import Permutation


def compute_automorphism_generators(dm: DartMap) -> list[Permutation]:
    """Return a generating set for ``Aut(dm)``.

    Parameters
    ----------
    dm : DartMap
        Input dart map.

    Returns
    -------
    list[Permutation]
        Generators as permutations on dart indices ``0..dm.num_darts-1``.
        Empty list if ``Aut(dm)`` is trivial (only the identity).

    Raises
    ------
    ImportError
        If pynauty is not installed.
    """
    generators, _order = _dartmap_automorphisms(dm)
    return generators


def automorphism_group_order(
    generators: list[Permutation], num_darts: int
) -> int:
    """Compute ``|Aut(dm)|`` by BFS closure of generators (pure Python).

    Parameters
    ----------
    generators : list[Permutation]
        Generating set for the group.
    num_darts : int
        Size of the permutation domain (number of darts).

    Returns
    -------
    int
        Order of the group generated by *generators*.

    Notes
    -----
    Uses a seen-set of permutation tuples.  Safe for groups up to roughly
    100 000 elements, which covers all Platonic solids and most polyhedra.
    For production use, prefer the order returned directly by
    :func:`~polygraph.interop.pynauty_adapter.dartmap_automorphisms`.
    """
    identity = tuple(range(num_darts))
    if not generators:
        return 1

    seen: set[tuple[int, ...]] = {identity}
    queue: list[tuple[int, ...]] = [identity]

    gen_mappings = [g.mapping for g in generators]
    inv_mappings = [g.inverse().mapping for g in generators]
    all_mappings = gen_mappings + inv_mappings

    while queue:
        current = queue.pop()
        for m in all_mappings:
            new = tuple(m[current[i]] for i in range(num_darts))
            if new not in seen:
                seen.add(new)
                queue.append(new)

    return len(seen)


def is_orientation_preserving(pi: Permutation, dm: DartMap) -> bool:
    """Return ``True`` iff *pi* commutes with ``phi``.

    Parameters
    ----------
    pi : Permutation
        A dart-map automorphism.
    dm : DartMap
        The dart map *pi* acts on.

    Returns
    -------
    bool
        ``True`` if ``pi(phi(d)) == phi(pi(d))`` for all darts *d*
        (orientation-preserving), ``False`` if *pi* reverses face traversal
        (orientation-reversing reflection).

    Notes
    -----
    Orientation-preserving automorphisms commute with both ``phi`` and
    ``sigma``.  Orientation-reversing automorphisms satisfy
    ``pi(phi(d)) == phi⁻¹(pi(d))`` instead.
    """
    phi = [dm.phi(d) for d in range(dm.num_darts)]
    for d in range(dm.num_darts):
        if pi[phi[d]] != phi[pi[d]]:
            return False
    return True
