"""Automorphism-group utilities for combinatorial maps."""

from __future__ import annotations

from collections import deque

from polygraph.interop.bliss_adapter import compute_automorphisms
from polygraph.structures.dart_map import DartMap
from polygraph.structures.permutation import Permutation


def compute_automorphism_generators(dm: DartMap) -> list[Permutation]:
    """Compute a generating set for the automorphism group of ``dm``.

    Parameters
    ----------
    dm : DartMap
        Input combinatorial map.

    Returns
    -------
    list[Permutation]
        A generating set for ``Aut(dm)`` represented on darts.

    Notes
    -----
    The current implementation starts from the full automorphism set and then
    greedily keeps only permutations that expand the generated subgroup.
    """
    automorphisms = compute_automorphisms(dm)
    if not automorphisms:
        return []

    identity = Permutation.identity(dm.num_darts)
    known: set[Permutation] = {identity}
    generators: list[Permutation] = []

    for candidate in automorphisms:
        if candidate in known:
            continue

        generators.append(candidate)
        frontier = deque([candidate])

        while frontier:
            current = frontier.popleft()
            if current in known:
                continue
            known.add(current)

            for generator in generators:
                for composed in (
                    current.compose(generator),
                    generator.compose(current),
                ):
                    if composed not in known:
                        frontier.append(composed)

    return generators


def automorphism_group_order(
    generators: list[Permutation], num_darts: int
) -> int:
    """Compute the order of the group generated by ``generators``.

    Parameters
    ----------
    generators : list[Permutation]
        Group generators acting on ``0..num_darts-1``.
    num_darts : int
        Size of permutation domain.

    Returns
    -------
    int
        Cardinality of the generated subgroup.

    Raises
    ------
    ValueError
        If a generator has a domain size different from ``num_darts``.
    """
    for generator in generators:
        if len(generator) != num_darts:
            raise ValueError("all generators must have size num_darts")

    identity = Permutation.identity(num_darts)
    known: set[Permutation] = {identity}
    frontier = deque([identity])

    while frontier:
        current = frontier.popleft()
        for generator in generators:
            composed = generator.compose(current)
            if composed not in known:
                known.add(composed)
                frontier.append(composed)

    return len(known)


def is_orientation_preserving(pi: Permutation, dm: DartMap) -> bool:
    """Return whether ``pi`` preserves the orientation of all face cycles.

    Parameters
    ----------
    pi : Permutation
        Candidate automorphism on darts.
    dm : DartMap
        Reference combinatorial map.

    Returns
    -------
    bool
        ``True`` if ``pi`` commutes with ``phi`` (face orientation preserving).

    Notes
    -----
    For orientable combinatorial maps, orientation-preserving automorphisms are
    exactly those commuting with the face permutation ``phi``.
    """
    if len(pi) != dm.num_darts:
        return False

    for dart in range(dm.num_darts):
        if pi[dm.phi(dart)] != dm.phi(pi[dart]):
            return False
    return True


__all__ = [
    "automorphism_group_order",
    "compute_automorphism_generators",
    "is_orientation_preserving",
]
