"""Orbit computation under permutation group actions on DartMaps.

Uses union-find (path-compressed) to partition elements into orbits
under the group generated by a set of permutations.  A single pass
over all generators is sufficient because union-find captures the
transitive closure; generator inverses are not required explicitly
since every element ``x`` is unioned with ``g[x]`` for all ``x``.

Public API
----------
compute_orbits
    Partition dart indices into orbits.
dart_orbits
    Orbits of darts under ``Aut(dm)``.
vertex_orbits
    Orbits of vertices under ``Aut(dm)``.
edge_orbits
    Orbits of undirected edges under ``Aut(dm)``.
face_orbits
    Orbits of faces under ``Aut(dm)``.
"""

from __future__ import annotations

from polygraph.structures.dart_map import DartMap
from polygraph.structures.permutation import Permutation

# ---------------------------------------------------------------------------
# Union-find helpers
# ---------------------------------------------------------------------------

def _make_uf(n: int) -> list[int]:
    """Return an initialised union-find parent array for ``n`` elements."""
    return list(range(n))


def _find(parent: list[int], x: int) -> int:
    """Return root of ``x`` with path compression."""
    while parent[x] != x:
        parent[x] = parent[parent[x]]  # path halving
        x = parent[x]
    return x


def _union(parent: list[int], x: int, y: int) -> None:
    """Merge the components containing ``x`` and ``y``."""
    rx, ry = _find(parent, x), _find(parent, y)
    if rx != ry:
        parent[rx] = ry


def _collect_orbits(
    parent: list[int], elements: list[int]
) -> list[list[int]]:
    """Group ``elements`` into orbits using a finalised parent array."""
    roots: dict[int, list[int]] = {}
    for e in elements:
        root = _find(parent, e)
        roots.setdefault(root, []).append(e)
    return list(roots.values())


# ---------------------------------------------------------------------------
# Public functions
# ---------------------------------------------------------------------------

def compute_orbits(
    generators: list[Permutation], n: int
) -> list[list[int]]:
    """Partition ``0..n-1`` into orbits under the generated group.

    Parameters
    ----------
    generators : list[Permutation]
        Generating set.  An empty list yields ``n`` singleton orbits.
    n : int
        Domain size (must equal ``len(g)`` for each generator ``g``).

    Returns
    -------
    list[list[int]]
        Disjoint, non-empty sublists partitioning ``range(n)``.
    """
    parent = _make_uf(n)
    for gen in generators:
        for x in range(n):
            _union(parent, x, gen[x])
    return _collect_orbits(parent, list(range(n)))


def dart_orbits(
    generators: list[Permutation], dm: DartMap
) -> list[list[int]]:
    """Return orbits of darts under the automorphism group.

    Parameters
    ----------
    generators : list[Permutation]
        Generating set for ``Aut(dm)`` on dart indices.
    dm : DartMap
        Input combinatorial map.

    Returns
    -------
    list[list[int]]
        Each sublist is a dart orbit.
    """
    return compute_orbits(generators, dm.num_darts)


def vertex_orbits(
    generators: list[Permutation], dm: DartMap
) -> list[list[int]]:
    """Return orbits of vertices under the automorphism group.

    Each vertex is represented by the smallest dart in its ``sigma``
    orbit (the representative dart convention used throughout the
    traversal layer).

    Parameters
    ----------
    generators : list[Permutation]
        Generating set for ``Aut(dm)`` on dart indices.
    dm : DartMap
        Input combinatorial map.

    Returns
    -------
    list[list[int]]
        Each sublist is a set of vertex representative darts in the
        same symmetry orbit.
    """
    # Build dart → vertex-representative map.
    dart_to_vrep: list[int] = [0] * dm.num_darts
    for cycle in dm.vertex_orbits():
        rep = min(cycle)
        for d in cycle:
            dart_to_vrep[d] = rep

    v_reps: list[int] = sorted({dart_to_vrep[d] for d in range(dm.num_darts)})
    # Map v_rep → compact index for union-find.
    idx = {r: i for i, r in enumerate(v_reps)}
    parent = _make_uf(len(v_reps))

    for gen in generators:
        for r in v_reps:
            image_rep = dart_to_vrep[gen[r]]
            _union(parent, idx[r], idx[image_rep])

    raw = _collect_orbits(parent, list(range(len(v_reps))))
    return [[v_reps[i] for i in group] for group in raw]


def edge_orbits(
    generators: list[Permutation], dm: DartMap
) -> list[list[int]]:
    """Return orbits of undirected edges under the automorphism group.

    Each edge is represented by the canonical dart ``min(d, alpha[d])``.

    Parameters
    ----------
    generators : list[Permutation]
        Generating set for ``Aut(dm)`` on dart indices.
    dm : DartMap
        Input combinatorial map.

    Returns
    -------
    list[list[int]]
        Each sublist is a set of canonical edge darts in the same
        symmetry orbit.
    """
    e_reps: list[int] = [d for d in range(dm.num_darts) if d < dm.alpha[d]]
    idx = {r: i for i, r in enumerate(e_reps)}
    parent = _make_uf(len(e_reps))

    for gen in generators:
        for r in e_reps:
            # Image of edge r: canonical dart of {gen[r], gen[alpha[r]]}.
            image_rep = min(gen[r], gen[dm.alpha[r]])
            _union(parent, idx[r], idx[image_rep])

    raw = _collect_orbits(parent, list(range(len(e_reps))))
    return [[e_reps[i] for i in group] for group in raw]


def face_orbits(
    generators: list[Permutation], dm: DartMap
) -> list[list[int]]:
    """Return orbits of faces under the automorphism group.

    Each face is represented by the smallest dart in its ``phi`` orbit.

    Parameters
    ----------
    generators : list[Permutation]
        Generating set for ``Aut(dm)`` on dart indices.
    dm : DartMap
        Input combinatorial map.

    Returns
    -------
    list[list[int]]
        Each sublist is a set of face representative darts in the same
        symmetry orbit.
    """
    dart_to_frep: list[int] = [0] * dm.num_darts
    for cycle in dm.face_orbits():
        rep = min(cycle)
        for d in cycle:
            dart_to_frep[d] = rep

    f_reps: list[int] = sorted({dart_to_frep[d] for d in range(dm.num_darts)})
    idx = {r: i for i, r in enumerate(f_reps)}
    parent = _make_uf(len(f_reps))

    for gen in generators:
        for r in f_reps:
            image_rep = dart_to_frep[gen[r]]
            _union(parent, idx[r], idx[image_rep])

    raw = _collect_orbits(parent, list(range(len(f_reps))))
    return [[f_reps[i] for i in group] for group in raw]
